services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    environment:
      JWT_SECRET: OOKEb2cD87RljYZ/uJHO9xgrMUDP4cc6hjofqE/DX8w=
      DATASOURCE_URL: jdbc:mysql://mysql-budgettracker.mysql.database.azure.com:3306/budgettracker
      DATASOURCE_USERNAME: hsu
      DATASOURCE_PASSWORD: Budgettracker01