# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - budgettracker03

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: hsuminhtet/budgettracker

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '21'

    - name: Build the application
      run: mvn clean package -DskipTests=true


    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_cc2b751deb254563a3bd12b345430245 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6f13bc8436c140c98e0de45605ebc11a }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t hsuminhtet/budgettracker:${{ github.run_number }} .

    - name: Push Docker image
      run: docker push hsuminhtet/budgettracker:${{ github.run_number }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'budgettracker03'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_566d15fcce80426eab1ba924db3f0e63 }}
        images: 'index.docker.io/hsuminhtet/budgettracker:${{ github.run_number }}'
#        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_cc2b751deb254563a3bd12b345430245 }}/hsuminhtet/budgettracker:${{ github.sha }}'